name: flutter_app_coriander2
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.1.3
  firebase_core: ^0.4.5
  firebase_analytics: ^1.0.4
  cloud_firestore: ^0.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

